Repository jjcourtney/PDJ-InfoCraft, pull requests merged in 2021-07, with the labels that each got.

#9 feat: Added backbone HTML
  index.html
Labels: enhancement

#11 Ticket2
  assets/style.css
  index.html
Labels: good first issue

#13 added the JS file
  assets/script.js
  index.html
Labels: enhancement

#14 feat: Added API call to Hypixel API
  assets/js/hypixelApi.js
  assets/js/script.js
  index.html
Labels: enhancement

#16 added serverJS and created getAPI func.
  assets/js/serverStatus.js
  index.html
Labels: enhancement

#20 Ticket4 styles
  assets/images/SteveSkin.png
  assets/images/infocraft.png
  assets/images/pdj.png
  index.html
Labels: enhancement

#22 Ticket21/create object server status
  assets/js/serverStatus.js
Labels: enhancement

#24 created promise for hypixel API, made obj w/stats
  assets/js/hypixelApi.js
Labels: enhancement

#26 created dynamic update feature w/Jquery
  assets/js/hypixelApi.js
  assets/js/script.js
  assets/js/serverStatus.js
  index.html
Labels: enhancement

#28 Feat: Updates status div
  assets/js/script.js
  assets/js/serverStatus.js
  index.html
Labels: enhancement

#37 Tiscket 32 add css link and style page
  assets/js/script.js
  index.html
Labels: enhancement

#39 feat: added func UTS to formatted date
  assets/js/script.js
Labels: enhancement

#40 Added readme file
  README.md
  assets/images/InfoCraftScreenShot.png
Labels: documentation

#42 styled form
  index.html
Labels: enhancement

#44 Arranged header and style form
  index.html
Labels: enhancement

#45 changed layout of header and backround colour
  assets/js/script.js
  index.html
Labels: enhancement

#46 Added bg image to header and changedcolours layout
  assets/images/minecraft-background-11.png
  assets/images/minecraftCover.png
  assets/js/script.js
  assets/style.css
  index.html
Labels: enhancement

#50 styled logo and footer
  assets/style.css
  index.html
Labels: enhancement

#53 feat: added responsive design
  index.html
Labels: enhancement

#55 feat: added search functionality
  assets/js/hypixelApi.js
  assets/js/script.js
  index.html
Labels: enhancement

#57 fxd issue w/ input size and centered text in foot
  index.html
Labels: bug

#58 #31 use local storage save previous searches
  assets/js/script.js
  index.html
Labels: enhancement

#59 removed excess w/s - added comments - refactor
  assets/css/style.css
  assets/js/hypixelApi.js
  assets/js/script.js
  index.html
Labels: bug, enhancement

#60 bug: fixed image path
  assets/css/style.css
Labels: bug
